---
abstract: 'Cookbook contains recipes to assist you in makeing your own Padre::Plugin'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-Cookbook
no_index:
  directory:
    - fbp
    - inc
    - share
    - t
    - xt
recommends:
  Test::Pod: 1.48
  Test::Pod::Coverage: 1.08
requires:
  Carp: 1.26
  Data::Dumper: 2.145
  Data::Printer: 0.35
  Moose: 2.0802
  Padre: 0.96
  constant: 1.27
  namespace::autoclean: 0.13
  parent: 0.225
  perl: 5.10.1
resources:
  bugtracker: http://padre.perlide.org/trac
  homepage: http://padre.perlide.org/trac/wiki/PadrePluginDialog
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Cookbook/
version: 0.24
