---
abstract: 'Cookbook contains recipes to assist you in makeing your own Padre::Plugin'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-Cookbook
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Data::Printer: 0.3
  Moose: 2.06
  POSIX: 1.17
  Padre: 0.96
  namespace::autoclean: 0.13
  perl: 5.10.1
resources:
  bugtracker: http://padre.perlide.org/trac
  homepage: http://padre.perlide.org/trac/wiki/PadrePluginDialog
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Cookbook/
version: 0.23
